from pathlib import Path

server = Path('Deployment/cloud/server.py')
text = server.read_text(encoding='utf-8')

old = '''def authenticate(request: dict[str, Any]) -> None:\n    if not AUTH_TOKEN:\n        return\n    params = request.get("params")\n    supplied = params.get("authToken") if isinstance(params, dict) else None\n    if not isinstance(supplied, str) or not hmac.compare_digest(supplied, AUTH_TOKEN):\n        raise PermissionError("authentication_required")\n'''
new = '''PUBLIC_METHODS = {\n    "Health",\n    "RuntimeInfo",\n    "ListWorkers",\n    "ListProjects",\n    "ListMemories",\n    "ListFiles",\n    "ListCheckpoints",\n    "ListGovernanceApprovals",\n    "ListDigitalHumanSessions",\n    "ListEvents",\n    "QueryCognitiveGraph",\n}\n\n\ndef authenticate(request: dict[str, Any], method: str | None = None) -> None:\n    if method in PUBLIC_METHODS:\n        return\n    if not AUTH_TOKEN:\n        return\n    params = request.get("params")\n    supplied = params.get("authToken") if isinstance(params, dict) else None\n    if not isinstance(supplied, str) or not hmac.compare_digest(supplied, AUTH_TOKEN):\n        raise PermissionError("authentication_required")\n'''
if old not in text:
    raise SystemExit('authenticate block not found')
text = text.replace(old, new, 1)
text = text.replace('''    authenticate(request)\n    return method, params\n''', '''    authenticate(request, method)\n    return method, params\n''', 1)
text = text.replace('''    openai_key = os.getenv("OPENAI_API_KEY") or os.getenv("SAREMBOK_AUTH_TOKEN") or api_key\n''', '''    openai_key = os.getenv("OPENAI_API_KEY") or api_key\n''', 1)
server.write_text(text, encoding='utf-8')

html = Path('frontend/index.html')
h = html.read_text(encoding='utf-8')
h = h.replace('''<div class="card-label" style="color:var(--emerald);">● RUNTIME CONNECTED</div>''', '''<div class="card-label" id="runtime-status" style="color:var(--text-muted);">● CONNECTING TO RUNTIME</div>''', 1)
h = h.replace('''<div class="card-val text-cyan" id="metric-mem">SQLite-WAL</div>''', '''<div class="card-val text-cyan" id="metric-mem">—</div>''', 1)
h = h.replace('''<div class="card-val" id="metric-agents">ARIA + 4 Workers</div>''', '''<div class="card-val" id="metric-agents">—</div>''', 1)
h = h.replace('''<div class="card-val text-emerald">sarembok.com</div>''', '''<div class="card-val text-emerald" id="metric-workers">—</div>''', 1)
old_js = '''        function connect() {\n            const loc = window.location;\n            const proto = loc.protocol === "https:" ? "wss:" : "ws:";\n            const wsUrl = (loc.hostname === "localhost" || loc.hostname === "127.0.0.1")\n                ? "ws://127.0.0.1:9120"\n                : `${proto}//${loc.host}/ws`;\n\n            ws = new WebSocket(wsUrl);\n            ws.onmessage = (e) => {\n                try {\n                    const data = JSON.parse(e.data);\n                    if (data.id && pending.has(data.id)) {\n                        const { res, rej } = pending.get(data.id);\n                        pending.delete(data.id);\n                        if (data.error) rej(data.error);\n                        else res(data.result);\n                    }\n                } catch(err) {}\n            };\n            ws.onclose = () => setTimeout(connect, 3000);\n        }\n'''
new_js = '''        function setRuntimeStatus(online, detail = "") {\n            const el = document.getElementById('runtime-status');\n            if (!el) return;\n            el.textContent = online ? '● RUNTIME ONLINE' : '● RUNTIME OFFLINE';\n            el.style.color = online ? 'var(--emerald)' : 'var(--text-muted)';\n            if (detail) el.title = detail;\n        }\n\n        function applyRuntimeInfo(info) {\n            if (!info) return;\n            const mem = document.getElementById('metric-mem');\n            const agents = document.getElementById('metric-agents');\n            const workers = document.getElementById('metric-workers');\n            if (mem) mem.textContent = info.storage || '—';\n            if (agents) agents.textContent = String(info.activeAgents ?? 0);\n            if (workers) workers.textContent = `${info.onlineWorkers ?? 0} / ${info.registeredWorkers ?? 0} workers online`;\n        }\n\n        function connect() {\n            const loc = window.location;\n            const proto = loc.protocol === "https:" ? "wss:" : "ws:";\n            const wsUrl = (loc.hostname === "localhost" || loc.hostname === "127.0.0.1")\n                ? "ws://127.0.0.1:9120"\n                : `${proto}//${loc.host}/ws`;\n\n            ws = new WebSocket(wsUrl);\n            ws.onopen = async () => {\n                setRuntimeStatus(true);\n                try {\n                    const info = await sendRPC("RuntimeInfo");\n                    applyRuntimeInfo(info);\n                } catch (err) {\n                    setRuntimeStatus(false, 'Runtime RPC unavailable');\n                }\n            };\n            ws.onmessage = (e) => {\n                try {\n                    const data = JSON.parse(e.data);\n                    if (data.id && pending.has(data.id)) {\n                        const { res, rej } = pending.get(data.id);\n                        pending.delete(data.id);\n                        if (data.error) rej(data.error);\n                        else res(data.result);\n                    }\n                } catch(err) {}\n            };\n            ws.onerror = () => setRuntimeStatus(false, 'WebSocket error');\n            ws.onclose = () => {\n                setRuntimeStatus(false, 'Connection closed');\n                setTimeout(connect, 3000);\n            };\n        }\n'''
if old_js not in h:
    raise SystemExit('connect block not found')
h = h.replace(old_js, new_js, 1)
old_catch = '''            } catch(e) {\n                aiMsg.innerHTML = `<strong style="color:var(--cyan);">ARIA:</strong> Directive received: "${escapeHtml(txt)}". Memory context reconciled.`;\n            }\n'''
new_catch = '''            } catch(e) {\n                aiMsg.innerHTML = `<strong style="color:#f59e0b;">RUNTIME:</strong> ${escapeHtml(e.message || 'The Sarembok runtime is unavailable. No action was executed.')}`;\n            }\n'''
if old_catch not in h:
    raise SystemExit('fake fallback block not found')
h = h.replace(old_catch, new_catch, 1)
h = h.replace('''<strong style="color:var(--cyan);">ARIA:</strong> System initialized. Ready to execute code synthesis, multi-agent pipelines, memory recall, or research directives.''', '''<strong style="color:var(--cyan);">ARIA:</strong> Runtime connection established when the cloud gateway is available. Commands execute only when the backend confirms execution.''', 1)
html.write_text(h, encoding='utf-8')
